logo_title: 郑可爱

style: black

favicon: /favicon.ico

menu:
  作品: /project
  标签: /tags
  分类: /categories
  # archives: /archives
  简历: /resume
  关于: /about
  Github: https://www.baidu.com

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false