Menu:
  Home: /
  Archives: /archives/
  About: /about/
  # Category: /category_archive
  # Tag: /tag_archive
  Github: https://github.com/vevlins/
  RSS: /atom.xml
  Search: true
  
Site:
  Motto: 日渐平庸

Intro:
  Avastar: img/avastar.jpeg
  Name: 郑可爱
  Brief: 地球上的一员
  SNS: 
    Weibo:  
    StackOverflow: 
    Github: https://baidu.com
    Pinterest: 
    Quora: 

CopyRight: 
  Author: Zyxzhongzhi
  License: CC BY-NC-SA 3.0 CN

Tip:
  Alipay: /img/qrcode.jpeg
  Wechat: /img/qrcode.jpeg

Comment:
  Id: 8d83609a651e972e308d
  Secret: 37e40c89a47e957f654e86f71c5caaccad0774de
  Repo: Zyxzhongzhi.github.io
  Owner: Zyxzhongzhi